Improve migration logic
aurora-is-near/aurora-engine-migration-tool pull request #21
Opened 2024-03-28 23:33 UTC by karim-en

Handle changes in the migration logic introduced here https://github.com/Near-One/aurora-eth-connector/pull/80.
* Removed proofs 
* Added `total_stuck_supply` to store the total balance for accounts with invalid format.
* Added combine command to combine the indexed and parsed state data so that we can run the migration command once.

2024-04-03 05:58 UTC, olga24912 requested changes

2024-04-03 11:04 UTC, mrLSD commented on src/migration.rs
> +                accounts.try_to_vec().expect("Failed serialize"),
Good qeustion

2024-04-03 12:08 UTC, karim-en commented on src/migration.rs
> +                accounts.try_to_vec().expect("Failed serialize"),
Nope, I didn't test it.
Yeh, true, the vec should be used instead

2024-04-04 13:01 UTC, karim-en commented on src/lib.rs
> -    pub proofs: Vec<String>,
We are going to use the `min_proof_acceptance_height` that has been added here https://github.com/Near-One/aurora-eth-connector/pull/74

2024-04-04 13:17 UTC, karim-en commented on src/migration.rs
> +                accounts.try_to_vec().expect("Failed serialize"),
Fixed 85d98c9889d37b60ceb563f09b30a82b0e21d7f7

2024-04-08 12:35 UTC, olga24912 approved these changes

2024-04-09 09:36 UTC, aleksuss approved these changes

2024-04-15 18:19 UTC, merged